Time::DATE_FORMATS[:default] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:datetime] = '%Y/%m/%d %H:%M'
Time::DATE_FORMATS[:date] = '%Y/%m/%d'
Time::DATE_FORMATS[:japanese] = '%Y年%m月%d日 %H時%M分'
Time::DATE_FORMATS[:time] = '%H:%M:%S'
Time::DATE_FORMATS[:MonTue] = '%Y/%m/%d(%a) %H:%M'
Date::DATE_FORMATS[:default] = '%Y/%m/%d'
